# Generated by Django 3.2.6 on 2021-08-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTipsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'infos'},
        ),
    ]
