# Generated by Django 3.2.6 on 2021-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTipsApp', '0002_alter_info_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='image',
            field=models.ImageField(default='default_subj.png', upload_to='subject_pics'),
        ),
    ]
