# Generated by Django 3.2.6 on 2021-08-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTipsApp', '0003_subjects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='image',
        ),
    ]
